name: build
on:
  pull_request:
  push:
  schedule:
    - cron: "11 21 * * *"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g dockerlint
      - run: dockerlint
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        target:
          - latest
          - jupyter
          - slim
          - alpine
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
      - run: task build:${{ matrix.target }}
