name: build
on:
  pull_request:
  push:
  schedule:
    - cron: "11 21 * * *"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g dockerlint
      - run: dockerlint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - run: make build
